
[general]
	#The material blacklist of this module.
	materialBlacklist = ["Aluminium", "Bedrock", "Brick", "CocoaButter", "EnderEye", "EnderPearl", "Endstone", "Fluix", "Milk", "NetherQuartz", "Netherrack", "PureNetherQuartz", "Stone", "Wheat", "Wood", "Ashes", "BrickNether", "BrickNetherGlazed", "BrickSeared", "CertusQuartz", "ChargedCertusQuartz", "ElvenElementium", "Manasteel", "Marshmallow", "Terrasteel"]

