
[general]
	#The material blacklist of this module.
	materialBlacklist = []
	#The materials to force generate passive forms for this module.
	passiveMaterialWhitelist = ["*", "*ingot_plain", "*gem_plain", "*crystal_plain", "*dust_plain"]

