
#Configurations for material Aluminium.
[general]
	#The alternative names of this material.
	alternativeNames = ["Aluminum"]
	#The byproducts of this material.
	extras = ["Iron","Aquamarine","Sapphire"]
	#Is the storage block of this material small (2x2).
	isSmallStorageBlock = false
	#The module blacklist of this material.
	moduleBlacklist = []
	#Should items of this material have the enchanted glow.
	hasEffect = false
	#The model type of the material.
	modelType = "metallic"
	#The color of this material.
	color = 0xd0d8dd

[molten]
	#The temperature of this molten fluid.
	temperature = 1000

